#配置mysql数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://122.51.193.191:3306/simple_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    table: flyway_schema_history_blog
    out-of-order: true
    placeholder-replacement: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#配置端口号
server:
  port: 8072

blog:
  es.url: http://localhost:8074/
  image:
    path: simple-blog

logging:
  level:
    # 全局等级
    root: warn
    com: info
  file:  log/simple-blog.log